services:
  bot:
    build: 
      context: .
      dockerfile: Containerfile
    
    volumes:
      - .:/app:Z
    env_file:
      - env.ini
    ports:
    - 5678:5678
    restart: always
    tty: true